version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: taskea-mysql
    environment:
      MYSQL_DATABASE: taskea
      MYSQL_USER: dani
      MYSQL_PASSWORD: Skateboard1
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: openjdk:21-jdk
    container_name: taskea-app
    depends_on:
      - mysql
    volumes:
      - ./target:/app
    working_dir: /app
    command: ["java", "-jar", "Taskea-0.0.1-SNAPSHOT.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskea
      SPRING_DATASOURCE_USERNAME: dani
      SPRING_DATASOURCE_PASSWORD: Skateboard1
    ports:
      - "8081:8080"

volumes:
  db_data:
